export const ADD_NODE = 'ADD_NODE';
export const UPDATE_NODE = 'UPDATE_NODE';

export const LOAD_ALL_CAMPAIGNS_REQUEST = 'LOAD_ALL_CAMPAIGNS_REQUEST';
export const LOAD_ALL_CAMPAIGNS_SUCCESS = 'LOAD_ALL_CAMPAIGNS_SUCCESS';
export const LOAD_ALL_CAMPAIGNS_FAILURE = 'LOAD_ALL_CAMPAIGNS_FAILURE';

export const LOAD_CAMPAIGN_REQUEST = 'LOAD_CAMPAIGN_REQUEST';
export const LOAD_CAMPAIGN_SUCCESS = 'LOAD_CAMPAIGN_SUCCESS';
export const LOAD_CAMPAIGN_FAILURE = 'LOAD_CAMPAIGN_FAILURE';

export const CREATE_CAMPAIGN_REQUEST = 'CREATE_CAMPAIGN_REQUEST';
export const CREATE_CAMPAIGN_SUCCESS = 'CREATE_CAMPAIGN_SUCCESS';
export const CREATE_CAMPAIGN_FAILURE = 'CREATE_CAMPAIGN_FAILURE';

export const LOAD_ALL_PEOPLE_REQUEST = 'LOAD_ALL_PEOPLE_REQUEST';
export const LOAD_ALL_PEOPLE_SUCCESS = 'LOAD_ALL_PEOPLE_SUCCESS';
export const LOAD_ALL_PEOPLE_FAILURE = 'LOAD_ALL_PEOPLE_FAILURE';

export const LOAD_PERSON_REQUEST = 'LOAD_PERSON_REQUEST';
export const LOAD_PERSON_SUCCESS = 'LOAD_PERSON_SUCCESS';
export const LOAD_PEOPLE_FAILURE = 'LOAD_PEOPLE_FAILURE';

export const CREATE_PERSON_REQUEST = 'CREATE_PERSON_REQUEST';
export const CREATE_PERSON_SUCCESS = 'CREATE_PERSON_SUCCESS';
export const CREATE_PERSON_FAILURE = 'CREATE_PERSON_FAILURE';
