export const ADD_NODE = 'ADD_NODE';
export const UPDATE_NODE = 'UPDATE_NODE';

export const LOAD_ALL_CAMPAIGNS_REQUEST = 'LOAD_ALL_CAMPAIGNS_REQUEST';
export const LOAD_ALL_CAMPAIGNS_SUCCESS = 'LOAD_ALL_CAMPAIGNS_SUCCESS';
export const LOAD_ALL_CAMPAIGNS_FAILURE = 'LOAD_ALL_CAMPAIGNS_FAILURE';
