export const ADD_NODE = 'ADD_NODE';
export const UPDATE_NODE = 'UPDATE_NODE';

export const LOAD_ALL_CAMPAIGNS_REQUEST = 'LOAD_ALL_CAMPAIGNS_REQUEST';
export const LOAD_ALL_CAMPAIGNS_SUCCESS = 'LOAD_ALL_CAMPAIGNS_SUCCESS';
export const LOAD_ALL_CAMPAIGNS_FAILURE = 'LOAD_ALL_CAMPAIGNS_FAILURE';

export const LOAD_CAMPAIGN_REQUEST = 'LOAD_CAMPAIGN_REQUEST';
export const LOAD_CAMPAIGN_SUCCESS = 'LOAD_CAMPAIGN_SUCCESS';
export const LOAD_CAMPAIGN_FAILURE = 'LOAD_CAMPAIGN_FAILURE';
